- import_tasks: cpp.yml
- import_tasks: python.yml
- import_tasks: tmux.yml
- import_tasks: ranger.yml
- import_tasks: git.yml
- import_tasks: nvim.yml
- import_tasks: nvim_python.yml
- import_tasks: zsh.yml
- import_tasks: ctags.yml
- import_tasks: fzf.yml
- import_tasks: npm.yml
- import_tasks: node.yml
